# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 1000
      min-spare: 30
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        http-only: true

knife4j:
  enable: true
  setting:
    custom-code: 500
    enable-footer-custom: false

spring:
  # ?? dev|test|prod
  profiles:
    active: dev
  application:
    name: api-boot
  jackson:
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB

storage:
  enabled: true
  config:
    # ?????local?aliyun?minio
    type: local
    domain: http://localhost:8080
  local:
    path: /Users/moqi/Documents/upload


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  # ???????package?????????
  typeAliasesPackage: top.mqxu.*.entity
  global-config:
    # ???????
    db-config:
      # ID??
      id-type: AUTO
      # ??????
      logic-delete-value: 1
      # ??????
      logic-not-delete-value: 0
    banner: false
  # ????
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
